project:
  type: "website"
  title: "Curso Nbdev"
  output-dir: _output
  render:
    - "index.qmd"
    - "contenido/*.qmd"
    - "contenido/weeks/week01/*.qmd"
    - "contenido/weeks/week02/*.qmd"
    - "contenido/weeks/week03/*.qmd"
    - "contenido/weeks/week04/*.qmd"
    - "contenido/weeks/week05/*.qmd"

execute:
  freeze: auto
website:
  title: "Curso Nbdeb"
  page-navigation: true
  reader-mode: true
  open-graph: true
  favicon: "figures/icons/course_favicon.png"
  search:
    location: navbar
    type: textbox
  sidebar:
    style: docked
    contents:
      - href: contenido/index.qmd
        text: "🏠 Home"
      
      - section: "Contenido"
        contents:
        - href: contenido/weeks/week01/page.qmd
          text: Presentación del concepto 
        - href: contenido/weeks/week02/slides.qmd
          text: Instalación prerequisitos
        - href: contenido/weeks/week03/1_pasos.qmd
          text: Generar biblioteca
        - href: contenido/weeks/week04/mas_modulos.qmd
          text: Más módulos
  navbar:
    background: primary
  page-footer:
    background: light
    left: "Copyright 2024, CentroGeo" 



bibliography: references/references.bib
csl: references/chicago-author-date.csl


format:
  html:
    author: Dr. [J. Miguel Salazar](#)
    author-meta: Dr. J. Miguel Salazar
    date-format: "DD MMMM YYYY"

    email-obfuscation: javascript
    link-external-newwindow: true
    link-external-icon: true
    link-external-filter: ^(?:http:|https:)\/\/(?:lse-dsi\.github\.io\/|localhost)

    theme:
      light: 
        - journal
        - css/custom.scss # I use this just to change the default colour
    css: 
      - css/custom_style.css
      - css/syllabus.css
    toc: true

#margin-header: |
# ![](/figures/logos/MY_INSTITUTION.png)

